### ISSUE TITLE
`avcodec_decode_video2` is deprecated

### ISSUE THREAD

**Issue by TonalidadeHidrica** [meh/rust-ffmpeg#129]
In [`codec:decoder::video::Video::decode`](https://github.com/meh/rust-ffmpeg/blob/master/src/codec/decoder/video.rs#L17) implementation, [`avcodec_decode_video2`](https://ffmpeg.org/doxygen/3.2/group__lavc__decoding.html#ga3ac51525b7ad8bca4ced9f3446e96532) function is used, but this is deprecated.  This should be replaced to an implementation using `avcodec_send_packet` and `avcodec_receive_frame` functions instead.

**Comment by lucaszanella** [comment]
I'm working on that

**Comment by meh** [comment]
Fixed on master.
