### ISSUE TITLE
PacketIter ignores errors

### ISSUE THREAD

**Issue by kornelski** [meh/rust-ffmpeg#133]
https://github.com/meh/rust-ffmpeg/blob/67b7f13305c457faa6f95f3a3d9921110e93d586/src/format/context/input.rs#L173

It would be better if this iterator returned `Result<(Stream<'a>, Packet), Error>` instead, so that the caller can handle errors (other than EOF).

With `Err(..) => ()` I'm worried that this could end up being an infinite loop if ffmpeg can't skip over the error.

**Comment by meh** [comment]
That's a very good point.

**Comment by meh** [comment]
Fixed on master.
