### ISSUE TITLE
cannot find value `AVCOL_PRI_EBU3213` in this scope

### ISSUE THREAD

**Issue by unlimitedcoder2** [meh/rust-ffmpeg#136]
```log
error[E0425]: cannot find value `AVCOL_PRI_EBU3213` in this scope
  --> /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/ffmpeg-0.3.0/src/util/color/primaries.rs:66:35
   |
66 |             Primaries::EBU3213 => AVCOL_PRI_EBU3213,
   |                                   ^^^^^^^^^^^^^^^^^ not found in this scope

error: aborting due to previous error

For more information about this error, try `rustc --explain E0425`.
error: could not compile `ffmpeg`.
```
Any idea why I am getting this error when trying to compile this package?

**Comment by shssoichiro** [comment]
The version of ffmpeg (specifically, libavutil) on your machine is too old and doesn't support that color primary.

I'm also experiencing this issue in CI, and I suspect it will be a big problem for end users of my crate who are not on Arch/Gentoo as well. So I'm going to put together a patch for dynamic version support.
