### ISSUE TITLE
this project vs ffmpeg-next?

### ISSUE THREAD

**Issue by xd009642** [meh/rust-ffmpeg#153]
So I was using https://github.com/zmwangx/rust-ffmpeg#readme as this seemed to be dormant but now i'm not so sure? Also will changes merged into ffmpeg-next be also merged here as well if they're useful?

**Comment by netcrns** [comment]
The plan is for me to take over, so there should be some activity as soon as our lives are more stable and I can dedicate some time to maintaining this properly.
From what I know, we've already cherry-picked things over from `ffmpeg-next` to here - is there something you feel we missed?

**Comment by xd009642** [comment]
Not that I'm aware just checking. I had a PR on ffmpeg-next so I guess I'll check if it's still applicable here and reopen it on this repo if it is :smile:
