### ISSUE TITLE
failed to run custom build command for `ffmpeg-sys v4.3.3`

### ISSUE THREAD

**Issue by Maxuvious** [meh/rust-ffmpeg#172]
--- stderr
  Using stack size: Ok(3145728)
  fatal error: '/usr/include/libavcodec/vaapi.h' file not found
  fatal error: '/usr/include/libavcodec/vaapi.h' file not found, err: true
  thread 'ffmpg-sys-build' panicked at 'Unable to generate bindings: ()', /home/max/.cargo/registry/src/github.com-1ecc6299db9ec823/ffmpeg-sys-4.3.3/build.rs:1279:10
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/b833ad56f46a0bbe0e8729512812a161e7dae28a/library/std/src/panicking.rs:575:5
     1: core::panicking::panic_fmt
               at /rustc/b833ad56f46a0bbe0e8729512812a161e7dae28a/library/core/src/panicking.rs:65:14
     2: core::result::unwrap_failed
               at /rustc/b833ad56f46a0bbe0e8729512812a161e7dae28a/library/core/src/result.rs:1791:5
     3: core::result::Result<T,E>::expect
               at /rustc/b833ad56f46a0bbe0e8729512812a161e7dae28a/library/core/src/result.rs:1070:23
     4: build_script_build::thread_main
               at ./build.rs:1276:24
     5: core::ops::function::FnOnce::call_once
               at /rustc/b833ad56f46a0bbe0e8729512812a161e7dae28a/library/core/src/ops/function.rs:507:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', /home/max/.cargo/registry/src/github.com-1ecc6299db9ec823/ffmpeg-sys-4.3.3/build.rs:629:10
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/b833ad56f46a0bbe0e8729512812a161e7dae28a/library/std/src/panicking.rs:575:5
     1: core::panicking::panic_fmt
               at /rustc/b833ad56f46a0bbe0e8729512812a161e7dae28a/library/core/src/panicking.rs:65:14
     2: core::result::unwrap_failed
               at /rustc/b833ad56f46a0bbe0e8729512812a161e7dae28a/library/core/src/result.rs:1791:5
     3: core::result::Result<T,E>::unwrap
               at /rustc/b833ad56f46a0bbe0e8729512812a161e7dae28a/library/core/src/result.rs:1113:23
     4: build_script_build::main
               at ./build.rs:623:5
     5: core::ops::function::FnOnce::call_once
               at /rustc/b833ad56f46a0bbe0e8729512812a161e7dae28a/library/core/src/ops/function.rs:507:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by kornelski** [comment]
ffmpeg 5 is not supported. Only ffmpeg 4.3 will work.

**Comment by Maxuvious** [comment]
> ffmpeg 5 is not supported. Only ffmpeg 4.3 will work.

Okay, thanks!

I found the cargo packages ffmpeg-next and ffmpeg-sys-next that support ffmpeg 5, but at some point it might be best to rewrite ffmpeg in rust completely... I assume this is just too daunting of a task and that's why it hasn't happened yet.
