### ISSUE TITLE
License

### ISSUE THREAD

**Issue by zetok** [meh/rust-ffmpeg#32]
Hello.

Currently `rust-ffmpeg` is licensed under WTFPL - license that is not recognised in some jurisdictions, which puts `rust-ffmpeg` on a level equal to proprietary code that can't be used.

Furthermore, WTFPL does not offer any sort of protection for someone who wrote the code - according to it, they can be hold liable for the code they wrote.

To help with those issues, CC0 could be used - it's on par with WTFPL when it comes to what it allows (it's a public domain license), is recognised in every jurisdiction, and also offers protection for code authors from being held liable for code they wrote.

To compare those 2:
https://tldrlegal.com/license/do-what-the-f*ck-you-want-to-public-license-%28wtfpl%29
https://tldrlegal.com/license/creative-commons-cc0-1.0-universal

Thus, I would like to ask whether it is possible to re-license `rust-ffmpeg` (and `rust-ffmpeg-sys`) to CC0?
Are there some reasons to keep WTFPL, instead of switching to CC0?

====
On a side note - it would seem quite likely that I will have to use `rust-ffmpeg` in some FOSS project(s?) I'll be doing in the future, and using something that uses WTFPL would make me feel uneasy - I would be afraid that WTFPL in some jurisdictions would affect ability of users' to use software because of legal reasons.

**Comment by meh** [comment]
WTFPL is effectively public domain where public domain is not legally recognized, it doesn't default back to proprietary.

And other than being public domain, it's a strong statement on my part.

Also I don't see how it would prevent users of your software from using it.
