### ISSUE TITLE
A new release to crates.io?

### ISSUE THREAD

**Issue by emk** [meh/rust-ffmpeg#45]
This looks like a really interesting library! I'd like to add optional ffmpeg support to my [substudy][] subtitle-processing crate, but it turns out that a crate on crates.io can't depend on a crate which is only distributed via GitHub.

Would it be possible to make a new release of the ffmpeg crate at some point so that I could try it out? Thank you very much for working on Rust video tools!

[substudy]: https://github.com/emk/substudy

**Comment by meh** [comment]
I released an alpha version of the crate, you will have to use `~0.2.0` as version for now, see [here](https://github.com/rust-lang/cargo/issues/952).

**Comment by emk** [comment]
Great! Thank you very much.

**Comment by meh** [comment]
No problem. I know the crate is lacking documentation currently, but I need more people using it to figure out if the API is ergonomic enough, and I don't want to write documentation that I might have to rewrite from scratch.

If you find any problems or have ideas feel free to open an issue.
