### ISSUE TITLE
failing to find `ffmpeg-sys` when running cargo build

### ISSUE THREAD

**Issue by benhinchley** [meh/rust-ffmpeg#52]
I am currently trying to build the `codec-info.rs` example and am currently getting this error message
I am fairly new to rust so not really sure what I should be doing to fix it
```
cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
no matching package named `ffmpeg-sys` found (required by `ffmpeg`)
location searched: registry https://github.com/rust-lang/crates.io-index
version required: ^2.8.0 
```

my `Cargo.toml` file is
```
[package]
name = "fastr"
version = "0.1.0"
authors = ["Benjamin Hinchley <benjaminhinchley@gmail.com>"]

[dependencies]
ffmpeg = "0.2.0-alpha.1"
```

**Comment by Ryman** [comment]
Related cargo issue: https://github.com/rust-lang/cargo/issues/2472#issuecomment-195832319

**Comment by benhinchley** [comment]
I have managed to solve my issue by changing `ffmpeg = "0.2.0-alpha.1"` to `ffmpeg = "*"`
