### ISSUE TITLE
New Codec Context from Codec

### ISSUE THREAD

**Issue by LuoZijun** [meh/rust-ffmpeg#62]
Hi, 
don't support new one  `ffmpeg::codec::Context` struct from one `ffmpeg::codec::codec::Codec` struct ?

why this make `CodecContext` from `Null` ?

Example:

```rust
let code_id: AVCodecID           = AVCodecID::AV_CODEC_ID_MPEG1VIDEO;
let mut codec: *const AVCodec    = avcodec_find_encoder(code_id);
// Alloc Context need `Codec` data.
let mut c: AVCodecContext = avcodec_alloc_context3(codec);
```

But in [/src/codec/context.rs#L36](https://github.com/meh/rust-ffmpeg/blob/master/src/codec/context.rs#L36) 
```rust
Context { ptr: avcodec_alloc_context3(ptr::null()), owner: None }
```

**Comment by meh** [comment]
It's proper usage, check the documentation for `avcodec_alloc_context3`.

**Comment by LuoZijun** [comment]
ah, ok.
