### ISSUE TITLE
Improve state transitions of codec::* structs

### ISSUE THREAD

**Issue by lummax** [meh/rust-ffmpeg#7]
Current
-------

The current state transitions in the `codec` module are as follows:

    1 context
    2 └── opened
    3     ├── decoder
          │   ├── audio
          │   ├── subtitles
          │   └── video
    4     └── encoder
              ├── audio
              ├── subtitles
              └── video

1. A `Context` is obtained from a `Stream` object (or created anew).
2. This context is opened using the right `Codec` with `avcodec_open2()`.
3. A possible `Decoder` is created from the opened `Context`.
4. A possible `Encoder` is created from the opened `Context`.

Fields from `AVCodecContext` are exposed with getter/setter methods (primarily) from step 3/4 onwards.

This scheme works great for decoding as we are intrested in the fields in `AVCodecContext` set by the demuxer (`avformat_find_stream_info()`) or the encoder (`avcodec_open2()`).

However this does not work for encoding. `libavcodec` seems to expect certain fields in `AVCodecContext` set before calling `avcodec_open2()` (for example the `time_base` field, see [here](https://www.ffmpeg.org/doxygen/2.7/structAVCodecContext.html#ab7bfeb9fa5840aac090e2b0bd0ef7589)).  The current architecture does not allow this, as the setters are defined below the `Encoder` state (and `avcodec_open2()` needs to be called in step 2.).

New
---

I propose the following new schema:

    1   context
    2   ├── decoder_context
    2.1 │   └── opened_context
    2.2 │       ├── audio
    2.3 │       ├── subtitles
    2.4 │       └── video
    3   └── encoder_context
    3.1     ├── audio
            │   └── opened
    3.2     ├── subtitles
            │   └── opened
    3.3     └── video
               └── opened

1. A `Context` is obtained from a `Stream` object (or created anew).
   Common setters (like `set_threading()`) are defined here.
2. A 'Decoder' can be created by state transition. This decoder exposes getter methods for fields set by the demuxer (like `bits_per_coded_sample` see [here](https://www.ffmpeg.org/doxygen/2.7/structAVCodecContext.html#a5273a8cf73ef598d632c6eee1379d5ad)).
   1. The `Decoder` can be opened (`avcodec_open2()` in the background plus state transition). This opened decoder exposes more getter functions for fields set by the decoder common to all streams.
   2. An opened `Audio` decoder exposes getter functions for audio-specific fields and a `decode()` function.
   3. An opened `Subtitles` decoder exposes getter functions for subtitle-specific fields and a `decode()` function.
   4. An opened `Video` decoder exposes getter functions for video-specific fields and a `decode()` function.
3. An `Encoder` can be created by state transition.
   1. An `Audio` encoder can be created by state transition which exposes audio encoder specific setter functions. This can be opened with `avcodec_open2()` and a state transition to expose a `encode()` function.
   2. An `Subtitles` encoder can be created by state transition which exposes subtitle encoder specific setter functions. This can be opened with `avcodec_open2()` and a state transition to expose a `encode()` function.
   3. An `Video` encoder can be created by state transition which exposes video encoder specific setter functions. This can be opened with `avcodec_open2()` and a state transition to expose a `encode()` function.

I would start on implementing this to see if its possible and ergonomic.  Feedback is welcome :).

**Comment by meh** [comment]
Sounds good, do you have any code examples so it's a little more clear from the API side how things will look?

**Comment by meh** [comment]
Also to avoid trumping on your work, I'm going to do the `Stream` and `StreamMut` changes now.

**Comment by lummax** [comment]
https://github.com/lummax/rust-ffmpeg/tree/improve-codec-transitions contains the first part (decoder) of the changes. See https://github.com/lummax/rust-ffmpeg/blob/improve-codec-transitions/examples/metadata.rs#L25 for the changed API.

**Comment by meh** [comment]
Sounds good, just please leave `time_base` in even if it's deprecated, I use it :stuck_out_tongue:

**Comment by lummax** [comment]
Do you use in on `AVCodeContext` or on `AVStream`? Because only the use on `AVCodeContext` (if decoding) is deprecated.

**Comment by meh** [comment]
Ah, I use it on `AVStream`, feel free to remove it altogether then.
