### ISSUE TITLE
Invalid array size in unsafe blocks in frame::Video causes SIGSEGV

### ISSUE THREAD

**Issue by YaLTeR** [meh/rust-ffmpeg#80]
Example: https://github.com/meh/rust-ffmpeg/blob/master/src/util/frame/video.rs#L302
This assumes that height = self.height() for all planes, but for formats like YUV420P the Cb and Cr planes are actually only height / 2, which causes the returned slice to be 2x larger than the actual memory and causes SIGSEGVs when trying to access the out of bounds data.

**Comment by YaLTeR** [comment]
I found the ffmpeg code that determines chroma height based on luma height: https://www.ffmpeg.org/doxygen/2.3/imgutils_8c_source.html#l00137

I'm willing to add proper handling of this, how would it best done? Should I use that function and cache the result somewhere? Perhaps the values should be hardcoded in ffmpeg for each Pixel format?

**Comment by meh** [comment]
I guess the way to go would be to add a wrapper for `AVPixFmtDescriptor` and reimplement the logic, unless I'm reading that code incorrectly it uses `log2_chroma_h` to find the right height.

**Comment by YaLTeR** [comment]
Is there anything I should change or add in that PR?

**Comment by meh** [comment]
Could you fix those two nitpicks I left?

**Comment by YaLTeR** [comment]
Which ones? I don't see any comments.

**Comment by meh** [comment]
https://github.com/meh/rust-ffmpeg/pull/85/files#diff-fb149114906f9e6c60d6c1d6e3fd7f2fR304 and https://github.com/meh/rust-ffmpeg/pull/85/files#diff-c003f9ba1df4ad90bc437f54da778d37R259 .

**Comment by YaLTeR** [comment]
Updated, I hope that's what you meant because there are still no comments (did you leave any?)

**Comment by meh** [comment]
Nope, I can see the comments, I'm attaching a screenshot, unsure what's going on with GitHub on your end.


![last](https://user-images.githubusercontent.com/40204/27347187-fc4e7a52-55ef-11e7-83c9-70510d0d7301.png)

**Comment by YaLTeR** [comment]
Did you press the finish review button?

**Comment by meh** [comment]
Welp, I'm dumb! Sorry, you should be able to see them now.

**Comment by YaLTeR** [comment]
Applied the changes.
