### ISSUE TITLE
Release to crates.io

### ISSUE THREAD

**Issue by kornelski** [meh/rust-ffmpeg#99]
The version from master (apart from blocker #97) works well for me, but the same code ran with version on crates.io crashes with:

> Assertion desc failed at libswscale/swscale_internal.h:668
> Abort trap: 6

Could you release the latest version to crates.io? I'd like to publish my crate as well, and can't with a git URL.

**Comment by expenses** [comment]
👍

**Comment by Boscop** [comment]
Any update on this? :)

**Comment by kornelski** [comment]
The last published version from October is far behind now

**Comment by meh** [comment]
I'm planning to do a new release soon, I just want to make sure the new AVIO stuff works, so as soon as the stuff I'm working on seems to be stable for production, I'll publish.

**Comment by kornelski** [comment]
Evidently, this crate is dead.
